// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(lab_3_database_Context))]
    [Migration("20231010120812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("app.Plane", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("needs_repair")
                        .HasColumnType("INTEGER");

                    b.Property<string>("prod_country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wings_width")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaneId");

                    b.ToTable("Planes");
                });
#pragma warning restore 612, 618
        }
    }
}
