// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(lab_3_database_Context))]
    [Migration("20231116151416_migrationLab7")]
    partial class migrationLab7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("app.Car", b =>
                {
                    b.Property<int>("carId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("max_speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("prod_year")
                        .HasColumnType("INTEGER");

                    b.Property<float>("time0_100")
                        .HasColumnType("REAL");

                    b.Property<bool>("was_in_accident")
                        .HasColumnType("INTEGER");

                    b.HasKey("carId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("app.Plane", b =>
                {
                    b.Property<int>("planeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("needs_repair")
                        .HasColumnType("INTEGER");

                    b.Property<string>("prod_country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wings_width")
                        .HasColumnType("INTEGER");

                    b.HasKey("planeId");

                    b.ToTable("Planes");
                });
#pragma warning restore 612, 618
        }
    }
}
