// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(lab_3_database_Context))]
    partial class lab_3_database_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("app.Car", b =>
                {
                    b.Property<int>("carId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("max_speed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("prod_year")
                        .HasColumnType("INTEGER");

                    b.Property<float>("time0_100")
                        .HasColumnType("REAL");

                    b.Property<bool>("was_in_accident")
                        .HasColumnType("INTEGER");

                    b.HasKey("carId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("app.Plane", b =>
                {
                    b.Property<int>("planeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepairCompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("needs_repair")
                        .HasColumnType("INTEGER");

                    b.Property<string>("prod_country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wings_width")
                        .HasColumnType("INTEGER");

                    b.HasKey("planeId");

                    b.HasIndex("RepairCompanyId");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("app.RepairCompany", b =>
                {
                    b.Property<int>("RepairCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RepairCompanyId");

                    b.ToTable("RepairCompanies");
                });

            modelBuilder.Entity("app.Plane", b =>
                {
                    b.HasOne("app.RepairCompany", "repairCompany")
                        .WithMany("Planes")
                        .HasForeignKey("RepairCompanyId");

                    b.Navigation("repairCompany");
                });

            modelBuilder.Entity("app.RepairCompany", b =>
                {
                    b.Navigation("Planes");
                });
#pragma warning restore 612, 618
        }
    }
}
